version: '3.9'
name: clone
services:
    api:
        container_name: clone_api
        depends_on:
            - mongo
        build: .
        image: clone_api
        restart: always
        ports:
            - '3000:3000'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        volumes:
            - './volumes/storage:/usr/clone/dist/public'
    mongo:
        container_name: clone_mongo
        image: mongo
        restart: unless-stopped
        volumes:
            - './volumes/mongo:/data'
        ports:
            - '27017:27017'
